### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by 28klotlucas2** [C3ald/Token-API#4]
Some pages return a 500 internal server error.

**Comment by TriangularDev** [comment]
As of 9:31PM 12/25/21:
[https://imgur.com/a/wOIiCYS](https://imgur.com/a/wOIiCYS)

**Comment by Ceald1** [comment]
> As of 9:31PM 12/25/21: https://imgur.com/a/wOIiCYS

Thank you for reporting the issue, the issue should be fixed and let me know if you experience any more issues :D

**Comment by Ceald1** [comment]
I removed certain pages to work on the api. I do plan on changing the pages a lot to something different to ensure privacy and security.

**Comment by Ceald1** [comment]
The issue should be fixed now
